site_name: OSG Security
site_url: https://osg-htc.org/security/
repo_url: https://github.com/osg-htc/security/
theme: 
  name: material
  custom_dir: osgthedocs

nav:
- Home: 'index.md'
- Security Team: 'SecurityTeamMembers.md'
- Security Announcements:
  - Overview: 'OSGSecurityAnnouncements.md'
  - Overview x86 vulnerabilities: 'OSGSecurityAnnouncements-x86.md'
- Announcement Details:
    - OSG-SEC-2023-09-26 CRITICAL PMIx race condition vulnerability affecting Slurm: './vulns/OSG-SEC-2023-09-26.md'
    - OSG-SEC-2023-08-01 MEDIUM OpenJDK TLS vulnerability: './vulns/OSG-SEC-2023-08-01.md'
    - OSG-SEC-2023-07-28 HIGH OpenSSH remote code execution: './vulns/OSG-SEC-2023-07-28.md'
    - OSG-SEC-2023-06-30 CRITICAL Go programming language vulnerabilities: './vulns/OSG-SEC-2023-06-30.md'
    - OSG-SEC-2023-05-31 UPDATE on setuid-mode Apptainer exploit: './vulns/OSG-SEC-2023-05-31.md'
    - OSG-SEC-2023-05-24 MEDIUM multiple git vulnerabilities: './vulns/OSG-SEC-2023-05-24.md'
    - OSG-SEC-2023-05-18 HIGH Linux kernel user-after-free flaw in TLS protocol: './vulns/OSG-SEC-2023-05-18.md'
    - OSG-SEC-2023-05-17 HIGH Flaw in Linux kernel Netfilter module: './vulns/OSG-SEC-2023-05-17.md'
    - OSG-SEC-2023-04-26_2 MEDIUM GNU Emacs Org Mode arbitrary command injection: './vulns/OSG-SEC-2023-04-26_2.md'
    - OSG-SEC-2023-04-26 HIGH setuid-mode Apptainer exploit: './vulns/OSG-SEC-2023-04-26.md'
    - OSG-SEC-2023-04-25 CRITICAL Linux Kernel OverlayFS: './vulns/OSG-SEC-2023-04-25.md'
    - OSG-SEC-2023-04-05 HIGH Apache HTTP request splitting: './vulns/OSG-SEC-2023-04-05.md'
    - OSG-SEC-2023-03-08 HIGH multiple Linux kernel vulnerabilities: './vulns/OSG-SEC-2023-03-08.md'
    - OSG-SEC-2023-02-28 MEDIUM Linux kernel use-after-free in mm/mremap: './vulns/OSG-SEC-2023-02-28.md'
    - OSG-SEC-2023-02-17 INFO OpenSSL vulnerability: './vulns/OSG-SEC-2023-02-17.md'
    - OSG-SEC-2023-01-24 HIGH sudoedit privilege escalation: './vulns/OSG-SEC-2023-01-24.md'
    - OSG-SEC-2022-11-02 HIGH OpenSSL buffer overflows: './vulns/OSG-SEC-2022-11-02.md'
    - OSG-SEC-2022-10-25 HIGH libksba integer overflow: './vulns/OSG-SEC-2022-10-25.md'
    - OSG-SEC-2022-10-17 HIGH Linux kernel use-after-free in cls_route filter: './vulns/OSG-SEC-2022-10-17.md'
    - OSG-SEC-2022-10-07 HIGH expat use-after-free: './vulns/OSG-SEC-2022-10-07.md'
    - OSG-SEC-2022-10-04 MEDIUM DNS BIND memory leaks: './vulns/OSG-SEC-2022-10-04.md'
    - OSG-SEC-2022-08-26 HIGH Linux systemd use-after-free vulnerability: './vulns/OSG-SEC-2022-08-26.md'
    - OSG-SEC-2022-08-10_2 HIGH Linux rsyslog heap-based buffer overflow: './vulns/OSG-SEC-2022-08-10_2.md'
    - OSG-SEC-2022-08-10 HIGH Linux kernel perf use-after-free flaw: './vulns/OSG-SEC-2022-08-10.md'
    - OSG-SEC-2022-07-05 HIGH Use-after-free vulnerability in the Linux kernel Netfilter subsystem: './vulns/OSG-SEC-2022-07-05.md'
    - OSG-SEC-2022-05-05 CRITICAL Vulnerability in Slurm authentication handling: './vulns/OSG-SEC-2022-05-05.md'
    - OSG-SEC-2022-03-31 CRITICAL Expat XML parser arbitrary code execution vulnerability: './vulns/OSG-SEC-2022-03-31.md'
    - OSG-SEC-2022-03-18 CRITICAL OOB memory access flaw in Linux kernel: './vulns/OSG-SEC-2022-03-18.md'    
    - OSG-SEC-2022-03-16 UPDATE - HIGH Severity DOS Vulnerability in OpenSSL: './vulns/OSG-SEC-2022-03-16_update.md'
    - OSG-SEC-2022-03-16 HIGH Severity DOS Vulnerability in OpenSSL: './vulns/OSG-SEC-2022-03-16.md'    
    - OSG-SEC-2022-03-15 HTCondor Security Release 8.8.16, 9.0.10, and 9.6.0: './vulns/OSG-SEC-2022-03-15.md'
    - OSG-SEC-2022-03-09 CRITICAL “dirtypipe” vulnerability in Linux Kernel 5.8 and above: './vulns/OSG-SEC-2022-03-09.md'
    - OSG-SEC-2022-02-17 CRITICAL ALERT ACTION REQUIRED xcache image purge notification: './vulns/OSG-SEC-2022-02-17.md'
    - OSG-SEC-2022-01-26 CRITICAL local privilege escalation in polkit's pkexec: './vulns/OSG-SEC-2022-01-26.md'
    - OSG-SEC-2022-01-25 CRITICAL heap buffer overflow vulnerability in Linux kernel for RHEL 8 and derivatives: './vulns/OSG-SEC-2022-01-25.md'
    - OSG-SEC-2022-01-05 Additional UPDATE on Log4J Vulnerability: './vulns/OSG-SEC-2022-01-05.md'
    - OSG-SEC-2021-12-17 UPDATE on Log4J Vulnerability: './vulns/OSG-SEC-2021-12-17.md'
    - OSG-SEC-2021-12-16 Vulnerability in golang/Singularity: './vulns/OSG-SEC-2021-12-16.md'
    - OSG-SEC-2021-12-13 CRITICAL Vulnerability in Java Library Log4j: './vulns/OSG-SEC-2021-12-13.md'
    - OSG-SEC-2021-12-02 RCE Vulnerability in NSS: './vulns/OSG-SEC-2021-12-02.md'
    - OSG-SEC-2021-11-03 Privilege Escalation Vulnerability in dCache: './vulns/OSG-SEC-2021-11-04.md'
    - OSG-SEC-2021-11-03 HIGH severity vulnerability in Apache HTTP mod_proxy: './vulns/OSG-SEC-2021-11-03.md'
    - OSG-SEC-2021-09-10 Vulnerability in Linux Kernel Traffic Control Subsystem: './vulns/OSG-SEC-2021-09-10-Vulnerability-in-Linux-Kernel-Traffic-Control-Subsystem.md'
    - OSG-SEC-2021-08-25 Vulnerabilities in JupyterLab and Jupyter Notebook: './vulns/OSG-SEC-2021-08-25-Vulnerabilities-in-JupyterLab-and-Jupyter-Notebook.md' 
    - OSG-SEC-2021-07-27 Vulnerabilities in HTCondor: './vulns/OSG-SEC-2021-07-27-Vulnerabilities-in-HTCondor.md' 
    - OSG-SEC-2021-07-22 Vulnerability in Linux kernel: './vulns/OSG-SEC-2021-07-22-Vulnerability-in-Linux-kernel.md' 
    - OSG-SEC-2021-05-27 Vulnerability in Singularity: './vulns/OSG-SEC-2021-05-27-Vulnerability-in-Singularity.md' 
    - OSG-SEC-2021-05-18 Vulnerability in SLURM CVE-2021-31215: './vulns/OSG-SEC-2021-05-18-Vulnerability-in-SLURM-CVE-2021-31215.md' 
    - OSG-SEC-2021-03-17 Vulnerabilities in SQUID: './vulns/OSG-SEC-2021-05-11-Vulnerabilities-in-Squid.md' 
    - OSG-SEC-2021-03-17 Vulnerabilities in iSCSI: './vulns/OSG-SEC-2021-03-17-Vulnerabilities-in-iSCSI.md' 
    - OSG-SEC-2021-01-28 vulnerabilities in HTCondor: './vulns/OSG-SEC-2021-01-28-vulnerabilities-in-HTCondor.md' 
    - OSG-SEC-2021-01-27 heap-based buffer overflow in sudo: './vulns/OSG-SEC-2021-01-27-heap-based-buffer-overflow-in-sudo.md' 
    - OSG-SEC-2020-09-22 CVE-2020-14386 Memory corruption in kernel on EL8 **UPDATE**: './vulns/OSG-SEC-2020-09-22-CVE-2020-14386-Memory-corruption-in-kernel-on-EL8-UPDATE.md'
    - OSG-SEC-2020-09-22 CVE-2020-14386 Memory corruption in kernel on EL8: './vulns/OSG-SEC-2020-09-22-CVE-2020-14386-Memory-corruption-in-kernel-on-EL8.md'
    - OSG-SEC-2020-08-31 Vulnerabilities in frontier-squid: './vulns/OSG-SEC-2020-08-31-Vulnerabilities-in-frontier-squid.md'
    - OSG-SEC-2020-05-05 Singularity and unprivileged user namespaces: './vulns/OSG-SEC-2020-05-05-Singularity-and-unprivileged-user-namespaces.md'
    - OSG-SEC-2020-03-26 Vulnerability in xrootd-scitokens Plugin: './vulns/OSG-SEC-2020-03-26-Vulnerability-in-xrootd-scitokens-plugin.md'
    - OSG-SEC-2020-02-07 Vulnerabilities in Frontier Squid: './vulns/OSG-SEC-2020-02-07-Vulnerabilities-in-frontier-squid.md'
    - OSG-SEC-2019-11-15 Vulnerability in Squid UPDATE 2: './vulns/OSG-SEC-2019-11-15-Vulnerability-in-Squid-UPDATE-2.md'
    - OSG-SEC-2019-11-11 Vulnerability in Squid UPDATE: './vulns/OSG-SEC-2019-11-11-Vulnerability-in-Squid-UPDATE.md'
    - OSG-SEC-2019-11-08 Vulnerability in Squid: './vulns/OSG-SEC-2019-11-08-Vulnerability-in-Squid.md'
    - OSG-SEC-2019-07-25 Vulnerability in Squid: './vulns/OSG-SEC-2019-07-25-Vulnerability-in-Squid.md'
    - OSG-SEC-2019-05-14 Vulnerability in Singularity: './vulns/OSG-SEC-2019-05-14-Vulnerability-in-Singularity.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity Update 2: './vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity-Update-2.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity Update: './vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity-Update.md'
    - OSG-SEC-2018-12-12 Critical vulnerability in Singularity: './vulns/OSG-SEC-2018-12-12-Critical-vulnerability-in-Singularity.md'
    - OSG-SEC-2018-10-18 Vulnerability in Linux kernel’s create_elf_tables() function Update: './vulns/OSG-SEC-2018-10-18-Vulnerability-in-Linux-kernel-Update.md'
    - OSG-SEC-2018-10-04 Vulnerability in RedHat Ceph Storage: './vulns/OSG-SEC-2018-10-04-Vulnerability-in-Red-Hat-Ceph-Storage.md'
    - OSG-SEC-2018-10-02 Vulnerability in Linux kernel’s create_elf_tables() function: './vulns/OSG-SEC-2018-10-02-Vulnerability-in-Linux-kernel.md'
    - OSG-SEC-2018-09-20 Vulnerability in AFS: './vulns/OSG-SEC-2018-09-20-Vulnerabilities-in-AFS.md'
    - OSG-SEC-2018-09-06 Vulnerability in Apache Struts: './vulns/OSG-SEC-2018-09-06-Apache-Struts-Vulnerability.md' 
    - OSG-SEC-2018-08-17 Foreshadow: './vulns/OSG-SEC-2018-08-17-Foreshadow.md'
    - OSG-SEC-2018-08-07 Data channel encryption not guaranteed: './vulns/OSG-SEC-2018-08-07-data-channel-encryption-not-guaranteed.md'
    - OSG-SEC-2018-07-05 Vulnerabilities in Singularity: './vulns/OSG-SEC-2018-07-05-Singularity-Vulnerabilities.md'
    - OSG-SEC-2018-07-03 BLAHP vulnerability: './vulns/OSG-SEC-2018-07-03-BLAHP-Vulnerability.md'
    - OSG-SEC-2018-05-23 CILogon OSG CA service retirement: './vulns/OSG-SEC-2018-05-23-OSG-CA-service-retirement.md'
    - OSG-SEC-2018-05-18 Multiple EL7 Linux kernel vulnerabilities: './vulns/OSG-SEC-2018-05-18-Multiple-EL7-Linux-kernel-vulnerabilities.md'
    - OSG-SEC-2018-05-08 Meltdown-Spectre Update: './vulns/OSG-SEC-2018-05-08-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-05-07 Unprivileged user namespaces in Singularity: './vulns/OSG-SEC-2018-05-07-Unprivileged-User-Namespaces-vulnerability.md'
    - OSG-SEC-2018-04-30 Multiple vulnerabilities in Singularity: './vulns/OSG-SEC-2018-04-30-Multiple-Singularity-Vulnerabilities.md'
    - OSG-SEC-2018-04-25 Including Let’s Encrypt CA in the OSG CA bundle: './vulns/OSG-SEC-2018-04-25-Including-Lets-Encrypt-in-OSG-CA-bundle.md'
    - OSG-SEC-2018-04-19 Critical vulnerability in Singularity Update: './vulns/OSG-SEC-2018-04-19-Critical-Vulnerability-in-Singularity-Update.md'
    - OSG-SEC-2018-04-17 Vulnerability in MariaDB MySQL: './vulns/OSG-SEC-2018-04-17-Vulnerability-in-MariaDB-MySQL.md'
    - OSG-SEC-2018-04-02 Critical vulnerability in Singularity: './vulns/OSG-SEC-2018-04-02-Critical-Vulnerability-in-Singularity.md'
    - OSG-SEC-2018-03-27 Vulnerability in SLURM: './vulns/OSG-SEC-2018-03-27-SLURM-Vulnerability.md'
    - OSG-SEC-2018-03-13 SAML Vulnerabilities affecting multiple implementations: './vulns/OSG-SEC-2018-03-13-SAML-Vulnerabilities-affecting-multiple-implementations.md'
    - OSG-SEC-2018-03-08 Limiting Singularity image types: './vulns/OSG-SEC-2018-03-08-Limiting-Singularity-image-types.md'
    - OSG-SEC-2018-03-05 Vulnerability in Singularity: './vulns/OSG-SEC-2018-03-05-Singularity-Vulnerability.md'
    - OSG-SEC-2018-02-28 Disable weak ciphers in SSL: './vulns/OSG-SEC-2018-02-28-Weak-SSL-ciphers.md'
    - OSG-SEC-2018-01-22 Meltdown-Spectre Update: './vulns/OSG-SEC-2018-01-22-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-01-10 Meltdown-Spectre Update: './vulns/OSG-SEC-2018-01-10-Meltdown-Spectre-Update.md'
    - OSG-SEC-2018-01-04 Meltdown-Spectre Update: './vulns/OSG-SEC-2018-01-04-Meltdown-Spectre.md'
- CILogon OSG CA:
  - CILogon OSG CA: 'OSGCertificateService.md'
  - Frequently Asked Questions (FAQ): 'CILogonOSGFAQ.md'
- Certificate Authorities (CA) Distribution: 'CaDistribution.md'
- OSG Security Policies & Procedures:
  - Including Let’s Encrypt signing certificate in OSG CA bundle: 'LetsEncryptOSGCAbundle.md'
  - Approved OSG Security Policies: 'OSGSecurityPolicies.md'
  - Site/VO Removal Policy: 'SiteVORemovalPolicy.md'
  - OSG Security Procedures: 'OSGSecurityProcedures.md'
  - Site/VO Removal Procedure: 'SiteVORemovalProcedure.md'
  - Secure Communications in OSG: 'SecureCommunicationsOSG.md'
  - Software Vulnerability Handling: 'SoftwareVulnerabilityHandling.md'
  - Incident Discovery Reporting: 'IncidentDiscoveryReporting.md'
  - Joining Security-SIG mailing list: 'fnal-mail-list-join.md'
- Integrated Security for the OSG:
  - Security Awareness for the OSG: 'SecurityAwarenessForTheOSG.md'
  - Security User Responsibilities: 'SecurityUserResponsibilities.md'
  - Security Site Responsibilities: 'SecuritySiteResponsibilities.md'

markdown_extensions:
  - admonition
